(function(g){var window=this;var r4=function(a){var b={format:a.F,languageCode:a.A,languageName:a.C,displayName:g.wI(a),kind:a.B,name:a.D,id:a.Ia,is_servable:a.K,is_default:a.isDefault,is_translateable:a.H,vss_id:a.G};a.o&&(a=a.o,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.o,id:a.id,is_default:a.isDefault});return b},s4=function(a){return a.o?a.o.languageCode:a.A},gDa=function(a,b,c){var d=new g.vI;
c||(d.F=1);d.A=a.A;d.C=a.C;d.D=a.D;d.B=a.B;d.isDefault=!1;d.H=a.H;d.G=a.G;d.J=a.J;d.o=b;return d},t4=function(a){return(a=g.Y(a.app,void 0))?a.G?a.G.C:0:0},u4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.eQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},v4=function(a,b,c,d,e){g.eQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},x4=function(a){a=void 0===a?{}:a;
var b="_"+w4++;return new v4(0,0x8000000000000,0,b,a)},y4=function(a,b,c,d,e,f,k){var l={};
g.Da(l,b);g.Da(l,a.params);g.Da(l,c);var m={};g.Da(m,b.Lb);a.params.Lb&&g.Da(m,a.params.Lb);g.Da(m,c.Lb);l.Lb=m;g.V.call(this,{I:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:1==l.bi?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},P:[{I:"span",N:"captions-text"}]});this.F=[];this.aa=!1;this.D=a;this.G=[];this.J=[];this.bb=e;this.Va=f;this.Ra=k;this.H=null;this.ka=.96*e;this.za=.96*f;this.B=l;this.Ha=c;this.C=this.o["captions-text"];this.Ba=null!=this.C.style["box-decoration-break"]||
null!=this.C.style["-webkit-box-decoration-break"];this.ga=d/360*16;this.type=0;this.ma=this.ga*hDa(m);a=new g.iG(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.kQ,this);a.subscribe("dragmove",this.jQ,this);a.subscribe("dragend",this.iQ,this);this.wa=this.pa=0;a="";this.B.windowOpacity&&(a=g.Vt(this.B.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.B.windowOpacity+")");b={"background-color":a,display:!1===this.B.isVisible?"none":"","text-align":iDa[this.B.textAlign]};this.Ba&&(b["border-radius"]=
a?this.ma/8+"px":"");(this.K=this.Ra.o("web_player_vertical_captions")&&(2==this.D.params.bi||3==this.D.params.bi))&&jDa(this,this.element);g.xh(this.element,b);switch(this.B.kh){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.T(this.element,"ytp-caption-window-bottom")}},jDa=function(a,b){var c="vertical-rl";
1==a.B.eG&&(c="vertical-lr");g.Jd&&(c="vertical-lr"==c?"tb-lr":"tb-rl");g.xh(b,"-o-writing-mode",c);g.xh(b,"-webkit-writing-mode",c);g.xh(b,"writing-mode",c);g.xh(b,"text-orientation","upright");3==a.D.params.bi&&(g.xh(b,"text-orientation",""),g.xh(b,"transform","rotate(180deg)"))},hDa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},z4=function(a,b){var c={},d=b.background?b.background:a.B.Lb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.B.Lb.backgroundOpacity;d=g.Vt(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ma/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ga*hDa(b)+"px";d=1;e=b.color||a.B.Lb.color;if(b.color||null!=b.textOpacity)e=g.Vt(e),d=null==b.textOpacity?a.B.Lb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.oz&&(k=e=b.oz);var l=a.ga/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.WE()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.B.Lb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Bf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.up&&(c.visibility="hidden");return c},kDa=function(a,b,c){a.aa=a.aa||!!c;
var d={};g.Da(d,a.B.Lb);g.Da(d,c||b.A);g.Da(d,a.Ha.Lb);c=a.G[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.up==!!c.up&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.G.length;e++)if(g.bc(d,a.G[e])){var f=a.J[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Rd("SPAN");g.xh(f,z4(a,e));a.J[0].appendChild(f);e=1}a.J.length=e;a.G.length=e}else a.J.length=0,a.G.length=0,f=g.Rd("SPAN"),g.xh(f,z4(a,d)),a.C.appendChild(f);k=!d.up;e=(c=g.w(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.F.length||!b.D){if(0<l||0!=a.F.length){var n=g.Rd("BR");f.appendChild(n)}k&&a.Ks(f)}m&&(k?a.H:f).appendChild(c?g.Sd(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.xh(k[c],z4(a,d)),g.xh(k[c],"font-size","50%");a.G.push(d);a.J.push(f);a.F.push(b)},lDa=function(){},B4=function(){this.C=this.A=this.mode=this.B=0;
this.D=new A4(this);this.F=new A4(this);this.o=[];this.clear()},nDa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{po:a,
qo:b,result:0};a=mDa[a];b=mDa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{po:a,qo:b,result:1}}else if(b&128&&1<=a&&31>=a)return{po:a,qo:b,result:2};return{po:a,qo:b,result:3}},pDa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.C&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.C=0,oDa(a.D,b,c,d))},qDa=function(a,b){a.o.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?pDa(a,d.jz,d.kz,b):1==d.type&&a.B&496&&oDa(a.F,d.jz,d.kz,b)}a.o.length=0},C4=function(){this.o=0},D4=function(){this.A=this.B=this.o=0},E4=function(){this.timestamp=this.Me=0},F4=function(a){this.B=[];
for(var b=0;15>=b;b++){this.B[b]=[];for(var c=0;32>=c;c++)this.B[b][c]=new E4}this.o=this.A=this.row=0;this.style=new C4;this.D=a;this.C=0},G4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.B[m][p];
if(0!=r.Me){0==c&&(c=m,d=p);n=String.fromCharCode(r.Me);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Me||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],r=p.Me,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=p.timestamp,v<=e&&(e=v),l+=n,p.reset()),32==m||0==r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},vDa=function(a,b){switch(a){case 0:return rDa[(b&127)-32];
case 1:return sDa[b&15];case 2:return tDa[b&31];case 3:return uDa[b&31]}return 0},H4=function(a){return a.B[a.row][a.A]},I4=function(a,b,c){2<=b&&1<a.A&&(--a.A,H4(a).Me=0);
var d=H4(a);d.timestamp=a.D.A+0;d.Me=vDa(b,c);32>a.A&&a.A++},wDa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.B[b+e][f].Go(a.B[c+e][f])},J4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},K4=function(a){a.row=0<a.o?a.o:1;
a.A=1;J4(a,0,15)},L4=function(a){this.C=a;
this.D=0;this.style=new C4;this.F=new F4(a);this.G=new F4(a);this.H=new F4(a);this.A=this.F;this.B=this.G;this.o=this.A},M4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:G4(d,c),K4(a.A),K4(a.B),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.C.mode=1<<d.C;e?d.A=1:d.o!=b&&(d.o>b?(G4(d,c),J4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},xDa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.C.mode=1<<a.o.C},yDa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.C.mode=1<<a.o.C},A4=function(a){this.A=a;
this.o=new D4;this.D=0;this.B=new L4(a);this.F=new L4(a);this.C=this.B},oDa=function(a,b,c,d){a.o.update();
b=nDa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.po;c=b.qo;if(32<=e||!e)a.A.mode&a.A.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.o,b&96&&I4(a,0,b),c&96&&I4(a,0,c),0!=b&&0!=c&&3==a.style.o&&G4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.B=e,b.A=c,b.o=2,b=e&8?a.F:a.B,a.C=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;wDa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));J4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:I4(b.o,0,32);break a;case 48:57==c?(b=b.o,H4(b).Me=0,32>b.A&&b.A++):I4(b.o,1,c&15)}break;case 2:c&32&&I4(b.o,2,c&31);break;case 3:c&32&&I4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:xDa(b);break;
case 33:b=b.o;1<b.A&&(--b.A,H4(b).Me=0);break;case 36:b=b.o;d=H4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.B[a][c]==d){for(;32>=c;c++)b.B[a][c].reset();break}break;case 37:M4(b,2,d);break;case 38:M4(b,3,d);break;case 39:M4(b,4,d);break;case 40:I4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.C.mode=1<<b.o.C;break;case 42:d=b.H;d.o=15;d.style.set(4);K4(d);yDa(b);break;case 43:yDa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:G4(a,d)}J4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;G4(a,d);wDa(a,b,b+1,a.o-1);J4(a,a.row,1)}break;case 46:J4(b.B,0,15);break;case 47:G4(b.A,d);d=b.B;a=b.C.A+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.B[c][e].timestamp=a;d=b.B;b.B=b.A;b.A=d;xDa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.o,32<(b.A+=c&3)&&(b.A=32)}}},N4=function(a){g.L.apply(this,arguments)},O4=function(a){N4.call(this);
this.A=a;this.o=null},zDa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Bf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");P4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new u4(a,b,c,d,n.nodeValue,e||0<m,g.Yb(k)?void 0:k));else{var p={};g.Da(p,k);zDa(a,b,c,d,e||0<m,n,p,l)}}},Q4=function(a,b){N4.call(this);
this.J=b;this.C={};this.K={};this.L={};this.D="_"+w4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},R4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},S4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},T4=function(a,b){var c=R4(a,b);
if(void 0!=c)return c},U4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return P4.test(c),c},ADa=function(a,b){var c={},d=b.getAttribute("ws");
g.Da(c,d?a.L[d]:a.F);d=T4(b,"mh");null!=d&&(c.Eu=d);d=T4(b,"ju");null!=d&&(c.textAlign=d);d=T4(b,"pd");null!=d&&(c.bi=d);d=T4(b,"sd");null!=d&&(c.eG=d);d=U4(b,"wfc");null!=d&&(c.windowColor=d);d=R4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);d=S4(b,"rb");void 0!=d&&(c.e6=d);return c},BDa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Da(c,a.K[d]);d=T4(b,"ap");null!=d&&(c.kh=d);d=R4(b,"cc");null!=d&&(c.Cs=d);d=R4(b,"ah");null!=d&&(c.hg=d);d=R4(b,"rc");null!=d&&(c.jn=d);d=R4(b,"av");null!=d&&(c.fi=d);return c},CDa=function(a,b,c,d){var e={};
g.Da(e,BDa(a,b));g.Da(e,ADa(a,b));d?g.bc(e,a.F)?(d=a.D,e=a.F):d="_"+w4++:d=b.getAttribute("id")||"_"+w4++;a=R4(b,"t")+c;b=R4(b,"d")||0x8000000000000;return new v4(a,b,0,d,e)},V4=function(a,b,c){this.G=c;
this.version=this.F=this.C=this.o=0;this.A=new window.DataView(a);this.B=[]},W4=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},X4=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},Y4=function(a,b){N4.call(this);
this.A=a;this.track="CC3"==b.C?4:0;this.o=new B4;this.o.B=1<<this.track},EDa=function(a){if(g.w(a))return!1;
a=new V4(a,8,0);return DDa(a)},DDa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=X4(a))return!1;
a.version=W4(a);if(1<a.version)return!1;W4(a);W4(a);W4(a);return!0},FDa=function(){this.A=[];
this.o=[]},Z4=function(a,b){return b?a.o.concat(a.A):a.o},$4=function(a,b){switch(b.B){case "asr":var c=a.A;
g.Ja(c,(0,g.B)(b.Nu,b))||c.push(b);break;default:c=a.o,g.Ja(c,(0,g.B)(b.Nu,b))||c.push(b)}},a5=function(){N4.call(this)},GDa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Bf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new u4(b,c,d,e.id,p.nodeValue,f||0<n,g.Yb(l)?void 0:l);m.push(p);var r=e;g.M(r,p);r.A.push(p)}else r={},g.Da(r,l),GDa(a,b,c,d,e,!0,p,r,m)}},b5=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},HDa=function(a,b,c,d){d=Object.assign({Eu:0},d);
return new v4(a,b,c,"_"+w4++,d)},c5=function(a,b){g.L.call(this);
this.J=a;this.nB=!!b;this.A=new FDa;this.G=[];this.o=null},JDa=function(a){var b={};
if(a=s4(a))b.lang=a,IDa.test(a)&&(b.bi=1);return b},d5=function(a,b){c5.call(this,a,b.wo);
this.C=void 0;this.B=null;this.G=b.captionTranslationLanguages},e5=function(){this.wb=[]},f5=function(a,b,c,d,e,f){g.L.call(this);
this.L=a;this.A=b;this.F=new e5;this.o=null;this.J=d;this.M=f;this.B=this.C=null;this.H=c;this.G=e||!1;this.K=new g.Cu(this.GB,1E3,this);g.M(this,this.K);this.D=new g.bG(this);g.M(this,this.D);g.X(b).experiments.o("html5_disable_captions_seek_complete")?this.D.R(b,"seekto",this.MC):this.D.R(b,"seekcomplete",this.lQ);this.MC(b.getCurrentTime());this.GB()},g5=function(a,b){b-=t4(a.A);
var c=a.o;a.o=g.Ga(a.H.Jg(b).o);c!=a.o&&a.M&&a.M()},KDa=function(a,b){var c=g.NL(b,a.L,{}).Ya(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.B=g.jF(c,d,3,100).then((0,g.B)(a.WU,a));a.C=b;c=a.F;d=a.C.o[0].Aa;var e=g.cb(c.wb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.wb[e-1]&&e<c.wb.length&&1==c.wb[e]-d?(g.Sa(c.wb,e),g.Sa(c.wb,e-1)):0<e&&1==d-c.wb[e-1]?c.wb[e-1]=d:e<c.wb.length&&1==c.wb[e]-d?c.wb[e]=d:(g.Za(c.wb,e,0,d),g.Za(c.wb,e+1,0,d)))},h5=function(a,b){c5.call(this,g.X(b));
this.B=a;this.D=b;this.C=null;this.F=!1;this.H=g.AN(g.X(this.D))&&!this.B.A},i5=function(a,b){var c=[],d;
for(d in a.B.o){var e=a.B.o[d];if(LDa(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,g.X(a.D).experiments.o("web_player_populate_live_caption_track_kind_killswitch")||(m=e.kind);c.push(new g.vI({id:d,format:3,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},j5=function(a,b){for(var c=g.q(b),d=c.next();!d.done;d=c.next())$4(a.A,d.value)},LDa=function(a,b){return g.MI(a.info.mimeType)?
b?g.FI(a.info)==b:!0:!1},MDa=function(a,b){return null!=b&&b in a.B.o?a.B.o[b]:null},k5=function(a,b,c){var d=[],e;
for(e in a.B.o){var f=a.B.o[e];if(LDa(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},l5=function(a,b,c,d,e,f,k){y4.call(this,a,b,c,d,e,f,k);
this.type=1},m5=function(a,b,c,d,e,f,k){y4.call(this,a,b,c,d,e,f,k);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.V=this.Z=this.ia=this.ha=0;this.L=this.M=this.O=window.NaN;this.Da=null;this.da=new g.Cu(this.bV,433,this);g.M(this,this.da)},n5=function(a){if(!a.ha){var b=g.Rd("SPAN");
g.xh(b,z4(a,a.B.Lb));a.C.appendChild(b);b.appendChild(g.Sd("M"));var c=b.offsetHeight,d=g.Rd("BR");b.appendChild(d);b.appendChild(g.Sd("M"));a.ha=b.offsetHeight-c;a.C.removeChild(b)}return a.ha},o5=function(a){if(!a.ia){var b=g.Rd("SPAN");
g.xh(b,z4(a,a.B.Lb));jDa(a,b);a.C.appendChild(b);b.appendChild(g.Sd("\u9b31"));var c=b.offsetWidth,d=g.Rd("BR");b.appendChild(d);b.appendChild(g.Sd("\u9b31"));a.ia=b.offsetWidth-c;a.C.removeChild(b)}return a.ia},NDa=function(a){if((0,window.isNaN)(a.O)){var b=a.B.Cs;
if(b){var c=g.Rd("SPAN");g.fe(c,"\u2013".repeat(b));g.xh(c,z4(a,a.B.Lb));a.C.appendChild(c);a.O=c.offsetWidth;a.C.removeChild(c)}else a.O=0}return a.O},ODa=function(a){if((0,window.isNaN)(a.M)){var b=a.B.Cs;
if(b){var c=g.Rd("SPAN");g.fe(c,"\u53e3".repeat(b));g.xh(c,z4(a,a.B.Lb));a.C.appendChild(c);a.M=c.offsetHeight;a.C.removeChild(c)}else a.M=0}return a.M},p5=function(a,b,c,d,e,f){e=void 0===e?!0:e;
c5.call(this,f||null,d);c=c||g.EE(a).hl||"";c=c.split("_").join("-");this.D=g.GE(a,{hl:c});this.C=b;this.F={};this.B=null;this.H=e},s5=function(a){g.sU.call(this,a);
this.B=g.X(a);this.C=a.getVideoData();this.za=g.QT(a);this.M=a;var b=null,c=g.SD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.BD(c));this.ba=b;this.D={Lb:{}};this.G={Lb:{}};this.L=[];this.O={};this.Z={};this.K=!1;b=this.C;c=this.M;this.ia=b.ik()&&null!=b.sa||null!=b.sa&&g.AN(g.X(c))&&!b.sa.A&&null!=b.sa.o.rawcc;this.Ba=this.C.un||this.B.un||this.ia;this.ma="3"==this.B.C;b=g.jU(a);c=!(!b||!b.vn());this.pa=!(!b||!b.pj());this.F=this.ma&&c&&!this.ia;this.da=!this.F&&this.ma&&this.pa&&
this.ia;this.o=this.A=this.H=this.J=this.V=this.ka=null;this.wa=!this.B.experiments.o("web_player_assume_format3_available_killswitch");c=b=null;this.F||(b=new g.zu(this.xG,void 0,this),g.M(this,b),c=new g.Cu(this.MW,2E3,this),g.M(this,c));this.aa=b;this.ga=c;this.Y=new g.bG(this);g.M(this,this.Y);this.F||this.Y.R(a,"resize",this.Yw);this.Y.R(a,"onPlaybackAudioChange",this.UR);this.Y.R(a,g.gQ("captions"),this.kO,this);this.Y.R(a,"crx_captions",this.lO,this);q5(this,r5(this,"display-settings")||{})},
PDa=function(a){if(1==a.B.oh||1==a.C.oh||"alwayson"==g.bP(a.C,"yt:cc"))return!0;
if(2==a.B.oh){var b=r5(a,"module-enabled");if(null!=b)return!!b}if(a.C.captionTracks.length)var c=a.player.getAudioTrack().rs;return"ON"==c||"on"==g.bP(a.C,"yt:cc")},t5=function(a,b){if(a.o&&(void 0===b||!b)||!a.C.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Xo||"FORCED_ON"==c.rs},v5=function(a,b){if(a.A){var c=Z4(a.A.A,b||a.Ba);
if(a.H&&a.H.o)return a.H.o;for(var d=[a.C.nh,a.B.nh,g.bP(a.C,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(s4(c[f])==d[e])return c[f];return a.H&&a.H.Ns?a.H.Ns:(d=c.find(function(a){return a.isDefault}))?d:c[0]||u5(a)}return null},u5=function(a){return a.H&&a.H.Xo},QDa=function(a,b){for(var c=g.jU(a.M).oa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},x5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&w5(a,"module-enabled",!!b));a.o=b;t5(a)&&(a.o=u5(a));a.load(d)},RDa=function(a,b){var c=g.n_(a.za,!0).height;
if(!c)return null;var d=a.za.Wa();switch(null!=b.params.Eu?b.params.Eu:1<b.A.length?1:0){case 1:return new l5(b,a.D,a.G,c,d.width,d.height,a.B.experiments);case 2:return new m5(b,a.D,a.G,c,d.width,d.height,a.B.experiments);default:return new y4(b,a.D,a.G,c,d.width,d.height,a.B.experiments)}},q5=function(a,b,c){var d=y5.Lb;
a.D={};g.Da(a.D,y5);a.D.Lb={};g.Da(a.D.Lb,d);a.G={Lb:{}};var e=b.backgroundOverride?a.G:a.D,f=b.background||d.background;P4.test(f);e.Lb.background=f;e=b.colorOverride?a.G:a.D;f=b.color||d.color;P4.test(f);e.Lb.color=f;e=b.windowColorOverride?a.G:a.D;f=b.windowColor||y5.windowColor;P4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Lb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.D;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Lb.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.Bf?3:d.bold?1:d.Bf?2:0);f=f.Lb;switch(e){case 1:f.bold=!0;delete f.Bf;break;case 2:delete f.bold;f.Bf=!0;break;case 3:f.bold=!0;f.Bf=!0;break;default:delete f.bold,delete f.Bf}e=b.textOpacityOverride?a.G:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Lb.textOpacity=f;e=b.windowOpacityOverride?a.G:a.D;f=b.windowOpacity;null==f&&(f=y5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.G:a.D;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Lb.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Lb.fontFamily=f;a.loaded&&a.Yw();c&&w5(a,"display-settings",b)},TDa=function(a,b){if(b&&!a.J){var c=x4({bi:0,
lang:"en"});a.J=[c,new u4(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.cU(a.player,a.J)}else!b&&a.J&&(SDa(a,a.J),a.J=null)},SDa=function(a,b){g.fU(a.player,b);
(0,g.D)(b,function(a){g.Ta(this.L,a)},a);
a.aa.Tj()},UDa=function(a,b){return a&&g.w(a)&&P4.test(a)?a:b},VDa=function(a,b){return g.sa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},WDa=function(a,b){return g.sa(a)&&!(0,window.isNaN)(a)?g.md(a,-2,4):b},r5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},w5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.nQ.prototype.zl=g.ca(12,function(){for(var a=g.Cd(window.document,"track",void 0,this.o),b=0;b<a.length;b++)g.Xd(a[b])});
g.lS.prototype.zl=g.ca(11,function(){this.A.zl()});
g.nQ.prototype.vn=g.ca(10,function(){return!!this.o.textTracks});
g.lS.prototype.vn=g.ca(9,function(){return this.A.vn()});
g.nQ.prototype.rl=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.lS.prototype.rl=g.ca(7,function(a){this.A.rl(a)});
g.sP.prototype.pj=g.ca(6,function(){});
g.nQ.prototype.pj=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.lS.prototype.pj=g.ca(4,function(){return this.A.pj()});
g.UJ.prototype.kp=g.ca(2,function(a){return(a=this.rh(a))?a.A:0});
g.eM.prototype.kp=g.ca(1,function(){return 0});
g.vI.prototype.Nu=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var IDa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,P4=/^#(?:[0-9a-f]{3}){1,2}$/i;var iDa=["left","right","center","justify"];var y5={windowColor:"#080808",windowOpacity:0,textAlign:2,kh:7,hg:50,fi:100,Lb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(u4,g.eQ);u4.prototype.toString=function(){return g.eQ.prototype.toString.call(this)};g.t(v4,g.eQ);v4.prototype.toString=function(){return g.eQ.prototype.toString.call(this)};
var w4=0;g.t(y4,g.V);g.h=y4.prototype;g.h.kQ=function(a,b){var c=g.Nh(this.element,this.element.parentElement);this.pa=a-c.x;this.wa=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.jQ=function(a,b){var c=g.Qh(this.element),d=a-this.pa-.02*this.bb,e=b-this.wa-.02*this.Va,f=(d+c.width/2)/this.ka*3;f=Math.floor(g.md(f,0,2));var k=(e+c.height/2)/this.za*3;k=Math.floor(g.md(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ka;d=100*g.md(d,0,1);c=(e+k/2*c.height)/this.za;c=100*g.md(c,0,1);this.D.params.kh=l;this.D.params.fi=c;this.D.params.hg=d;this.B.kh=l;this.B.fi=c;this.B.hg=d;this.kF()};
g.h.iQ=function(){g.Nq(this.element,"ytp-dragging")};
g.h.kF=function(){this.mj(this.F)};
g.h.Yb=function(){return this.type};
g.h.mj=function(a){var b=Math.min(this.pA(),this.ka),c=this.oA(),d="";3==this.D.params.bi&&(d="rotate(180deg)");g.xh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Zr(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.B.hg+2;d=this.B.kh;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.B.fi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.xh(this.element,a)};
g.h.Zr=function(a){var b;for(b=0;b<a.length&&a[b]==this.F[b];b++);if(this.aa||this.F.length>b)b=0,this.aa=!1,this.F=[],this.G=[],this.J=[],this.H=null,g.Vd(this.C);for(;b<a.length;b++)kDa(this,a[b])};
g.h.pA=function(){return 0};
g.h.oA=function(){return 0};
g.h.Ks=function(a){a.appendChild(g.Sd("\u00a0"));this.H=g.Rd("SPAN");a.appendChild(this.H);g.T(this.H,"caption-visual-line");a.appendChild(g.Sd("\u00a0"))};
g.h.toString=function(){return g.V.prototype.toString.call(this)};lDa.prototype.D=function(){};B4.prototype.clear=function(){this.C=this.A=this.mode=0;this.o=[];this.reset()};
B4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var mDa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];C4.prototype.set=function(a){this.o=a};
C4.prototype.get=function(){return this.o};
D4.prototype.clear=function(){this.o=0};
D4.prototype.update=function(){this.o=2==this.o?1:0};
D4.prototype.matches=function(a,b){return 0!=this.o&&a==this.B&&b==this.A};
E4.prototype.Go=function(a){this.Me=a.Me;this.timestamp=a.timestamp};
E4.prototype.reset=function(){this.timestamp=this.Me=0};
F4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0==d.Me?a+"_":a+String.fromCharCode(d.Me)}a+="\n"}return a};
F4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.o=0;this.A=this.row=1};
var rDa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],sDa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],tDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],uDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];L4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.B=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
A4.prototype.reset=function(a){this.D=a;this.o.clear();this.C=this.B;this.B.reset(a,0);this.F.reset(a,1)};g.t(N4,g.L);N4.prototype.reset=function(){};g.t(O4,N4);
O4.prototype.B=function(a){var b=a.firstChild;a=[];this.o||(this.o=x4(this.A),a.push(this.o));b=Array.from(b.childNodes);b=g.q(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=this.o.id,e=c.getAttribute("t");e=e?(0,window.parseInt)(e,10):1E3*(0,window.parseFloat)(c.getAttribute("start")||0);var f=c.getAttribute("d");f=f?(0,window.parseFloat)(f):1E3*(0,window.parseFloat)(c.getAttribute("dur")||0);d=c.getAttribute("w")||d;var k=!!c.getAttribute("append"),l=k?6:5;c=g.xs("<html>"+(c.firstChild&&
c.firstChild.nodeValue||"")+"</html>");zDa(e,f,l,d,k,c.firstChild,{},a)}return a};g.t(Q4,N4);Q4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
Q4.prototype.B=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.C,l={},m=c.getAttribute("p");m&&g.Da(l,this.C[m]);m=S4(c,"b");null!=m&&(l.bold=
m);m=S4(c,"i");null!=m&&(l.Bf=m);m=S4(c,"u");null!=m&&(l.underline=m);m=T4(c,"et");null!=m&&(l.charEdgeStyle=m);m=T4(c,"of");null!=m&&(l.offset=m);m=U4(c,"bc");null!=m&&(l.background=m);m=U4(c,"ec");null!=m&&(l.oz=m);m=U4(c,"fc");null!=m&&(l.color=m);m=T4(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=R4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=R4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=R4(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=T4(c,"rb");void 0!=c&&(l.SW=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.L[d]=ADa(this,c);break;case "wp":d=c.getAttribute("id"),this.K[d]=BDa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=CDa(this,d,e,!1);g.M(this,this.o);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!S4(d,"a");n=(R4(d,"t")||0)+n;var p=R4(d,"d")||5E3;m||
(!this.G&&this.A&&this.A.windowId==l&&this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=""));var r=m?6:5,v=this.C[d.getAttribute("p")],z=d.childNodes;z.length&&(this.G=null!=d.getAttribute("d"));for(var E=0;E<z.length;E++){var I=z[E];0<E&&(m=!0);var N=void 0;1==I.nodeType&&(N=I);if(N&&"s"==N.tagName)if(I=this.C[N.getAttribute("p")],!I||1!=I.SW||this.J&&!this.J.experiments.o("web_player_ruby_text_captions")){var Q=N;I=n;var Oa=p,pb=l,jc=m,ee=r;N=Q.textContent?Q.textContent:"";var Ia=
this.C[Q.getAttribute("p")];Q=R4(Q,"t")||0;I=new u4(I+Q,Oa-Q,ee,pb,N,jc,Ia)}else{I=n;Oa=p;pb=l;jc=m;ee=r;Ia=N;var Lc=z[E+1],Ad=z[E+2];Q=z[E+3];Ia.getAttribute("p");R4(Ia,"t");R4(Lc,"t");R4(Ad,"t");R4(Q,"t");N=g.Rd("RUBY");Ia=Ia.textContent;var Qd=g.Rd("SPAN");Qd.innerText=Ia;N.appendChild(Qd);Lc.getAttribute("p");Qd=g.Rd("RP");Ia=Lc.textContent;Qd.innerText=Ia;N.appendChild(Qd);Ad.getAttribute("p");Ia=Ad.textContent;Lc=g.Rd("RT");Lc.innerText=Ia;N.appendChild(Lc);Q.getAttribute("p");Ia=Q.textContent;
Q=g.Rd("RP");Q.innerText=Ia;N.appendChild(Q);I=new u4(I,Oa,ee,pb,N,jc,null);E+=3}else I=new u4(n,p,r,l,I.textContent||"",m,v);k.push(I);this.A=I}if(0<k.length)for(k[0].windowId==this.D&&(this.o=CDa(this,d,e,!0),g.M(this,this.o),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.M(l,k),l.A.push(k),c.push(k)}e=c}else e=[];return e};g.t(V4,lDa);V4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+w4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new v4(c,d-c,5,f,{textAlign:0,kh:0,hg:2.5*b,fi:5.33*a});e=new u4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.t(Y4,N4);Y4.prototype.B=function(a){a=new V4(a,a.byteLength,this.A);if(DDa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.C=X4(a)*(1E3/45):1==a.version&&(a.C=4294967296*X4(a)+X4(a)),a.F=W4(a);0<a.F;a.F--){var b=W4(a),c=W4(a),d=W4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.C,type:this.track,jz:c,kz:d,order:b.o.length}))}qDa(this.o,a);return a.B}return[]};
Y4.prototype.reset=function(){this.o.clear()};g.t(a5,N4);
a5.prototype.B=function(a,b){for(var c=[],d=a.split(XDa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!YDa.test(f)){var l=z5.exec(f);if(l&&4<=l.length){var m=b5(l[1]),n=b5(l[2])-m;m+=k;var p,r=p=void 0,v=void 0,z=void 0,E=l[3];l={textAlign:2};E=g.q(E?E.split(" "):[]);for(var I=E.next();!I.done;I=E.next())if(I=I.value.split(":"),2==I.length){var N=I[1];switch(I[0]){case "line":I=N.split(",");I[0].endsWith("%")&&(z=I[0],l.fi=Number.parseInt(z,10),2==I.length&&(v=I[1].trim()));break;case "position":I=N.split(",");
r=I[0];l.hg=Number.parseInt(r,10);2==I.length&&(p=I[1].trim());break;case "align":switch(N){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.fi=100,v||(v="end"));if(!r)switch(l.textAlign){case 0:l.hg=0;break;case 1:l.hg=100;break;default:l.hg=50}r=0;switch(v){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.kh=0>r||8<r?7:r;p=l;f=f.substring(z5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=HDa(m,n,5,r),n=new u4(m,n,5,k.id,p,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),g.M(k,n),k.A.push(n);else for(v=p.split(ZDa),1==v.length?(p=5,r=HDa(m,n,p,r)):(z=p=6,r=Object.assign({Cs:32},r),r=new v4(m,n,z,"_"+w4++,r)),c.push(r),z=m,l=0;l<v.length;l++)E=v[l],0==l%2?(I=g.xs("<html>"+E+"</html>"),I.getElementsByTagName("parsererror").length?
(N=I.createElement("span"),N.appendChild(I.createTextNode(E))):N=I.firstChild,GDa(this,z,n-(z-m),p,r,0<l,N,f,c)):z=b5(E)+k}z5.lastIndex=0}}return c};
var YDa=/^NOTE/,XDa=/(?:\r\n|\r|\n){2,}/,z5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ZDa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(c5,g.L);c5.prototype.ce=function(){this.o&&this.o.dispose();this.o=null};
c5.prototype.X=function(){g.L.prototype.X.call(this);this.ce()};
c5.prototype.RE=function(){return!1};g.t(d5,c5);g.h=d5.prototype;g.h.yu=function(a,b){var c=this.Ul(a),d=(0,g.B)(function(c){this.B=null;b(c.responseText,a)},this);
this.ce();this.B=g.OE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.zu=function(a,b,c,d){this.C=c;if(d)for(b=g.q(d.captionTracks),c=b.next();!c.done;c=b.next())$4(this.A,c.value);a()};
g.h.Ul=function(a){var b=a.Ya(),c={};if(this.C||a.F)c.fmt=this.C||"srv"+a.F;a.o&&(c.tlang=a.o.languageCode);return g.GE(b,c)};
g.h.ce=function(){c5.prototype.ce.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.ce();c5.prototype.X.call(this)};e5.prototype.contains=function(a){a=g.cb(this.wb,a);return 0<=a||0>a&&1==(-a-1)%2};
e5.prototype.length=function(){return this.wb.length/2};g.t(f5,g.L);g.h=f5.prototype;g.h.X=function(){g.L.prototype.X.call(this);this.B&&this.B.cancel()};
g.h.MC=function(a){var b=this;if(this.H.hk())var c=this.D.R(this.A,"progresssync",function(){b.H.index.Pb()&&(b.reset(),b.o=null,g5(b,b.A.getCurrentTime()),b.D.Ka(c))});
else g5(this,a)};
g.h.lQ=function(){g5(this,this.A.getCurrentTime())};
g.h.reset=function(){this.F=new e5;this.B&&(this.B.cancel(),this.B=null)};
g.h.GB=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Tg(a);!a||this.B||this.o&&30<this.o.startTime-this.A.getCurrentTime()||(a=this.o,a=a.o.qk(a),!g.X(this.A).experiments.o("disable_captions_unknown_requests")&&!a.o[0].duration)||(this.F.contains(a.o[0].Aa)||KDa(this,a),this.o=g.Ga(a.o));this.K.start()};
g.h.WU=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status;if(!g.X(this.A).experiments.o("disable_captions_redirects_redux")){var c=g.jM(a);if(c){a=g.NL(this.C,this.L,{});b=this.C;g.IL(b.A,a,c);b.requestId=a.get("req_id");KDa(this,this.C);return}}b||null===this.J||(this.G?this.J(a.response,1E3*(this.C.o[0].startTime+t4(this.A))):this.J(a.responseText,1E3*(this.C.o[0].startTime+t4(this.A))));this.B=this.C=null};g.t(h5,c5);g.h=h5.prototype;g.h.yu=function(a,b){this.ce();var c=MDa(this,a.getId());c||(c=a.A,c=this.B.A?k5(this,c,"386")||k5(this,c,"387"):k5(this,c));if(c){var d=c.index.kp(c.index.wf());g.X(this.D).experiments.o("html5_disable_caption_starttime")||(d-=c.index.Zd(c.index.wf()));d*=1E3;this.C=new f5(new g.pL,this.D,c,function(c,f){b(c,a,f,d)},this.H||g.JI(c.info),(0,g.B)(function(){this.C&&this.C.reset();
this.o&&this.o.reset();this.F=!0},this))}};
g.h.RE=function(){var a=this.F;this.F=!1;return a};
g.h.zu=function(a){if(this.H)$4(this.A,new g.vI({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})),$4(this.A,new g.vI({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}));else if(this.B.A){var b=i5(this,"386");b.length?j5(this,b):j5(this,i5(this,"387"))}else j5(this,i5(this));a()};
g.h.ce=function(){c5.prototype.ce.call(this);this.C&&(this.C.dispose(),this.C=null)};
g.h.Ul=function(){return""};
g.h.X=function(){this.ce();c5.prototype.X.call(this)};g.t(l5,y4);l5.prototype.Zr=function(a){var b=this.D.A;y4.prototype.Zr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Da(d,c.A);g.Da(d,$Da);var e=c.A;var f=d}kDa(this,c,d)}};
var $Da={up:!0};g.t(m5,y4);g.h=m5.prototype;g.h.kF=function(){g.Eu(this.da)};
g.h.bV=function(){g.Nq(this.element,"ytp-rollup-mode");this.mj(this.Da,!0)};
g.h.pA=function(){return this.K?this.D.params.jn*o5(this):this.Z};
g.h.oA=function(){return this.K?this.V:this.D.params.jn*n5(this)};
g.h.Ks=function(a){y4.prototype.Ks.call(this,a);g.xh(this.H,"display","inline-block")};
g.h.mj=function(a,b){this.Da=a;if(!this.K&&!n5(this)||this.K&&!o5(this))y4.prototype.mj.call(this,a);else{for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));c=this.Z;d=this.V;this.V=this.Z=0;y4.prototype.mj.call(this,a);this.K?(c=this.C.offsetHeight+1,this.V=Math.max(ODa(this),d,c),c=this.D.params.jn*o5(this)-this.C.offsetWidth,1!=this.D.params.eG&&(c*=-1),c!=this.L&&(b||(0,window.isNaN)(this.L)||(g.T(this.element,"ytp-rollup-mode"),
g.Du(this.da)),g.xh(this.C,"transform",c?"translateX("+c+"px)":""),this.L=c)):(d=this.C.offsetWidth+1,this.Z=Math.max(NDa(this),c,d),c=this.D.params.jn*n5(this)-this.C.offsetHeight,c!=this.L&&(b||(0,window.isNaN)(this.L)||(g.T(this.element,"ytp-rollup-mode"),g.Du(this.da)),g.xh(this.C,"transform",c?"translateY("+c+"px)":""),this.L=c));y4.prototype.mj.call(this,a)}};g.t(p5,c5);g.h=p5.prototype;g.h.yu=function(a,b){var c=this.Ul(a),d=(0,g.B)(function(c){this.B=null;b(c.responseText,a)},this);
this.ce();this.B=g.OE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.zu=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.nB&&(b.asrs=1);d=g.GE(d,b);b=(0,g.B)(function(b){this.B=null;if((b=b.responseXML)&&b.firstChild){for(var d=c||null,e=g.q(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("lang_code");var n=m.getAttribute("lang_translated"),p=m.getAttribute("name"),r=m.getAttribute("kind"),v=m.getAttribute("id"),z="true"==m.getAttribute("lang_default"),E="true"==m.getAttribute("cantran"),
I=m.getAttribute("vss_id"),N=d;if(!N)if(this.H)N=3;else{N=1;m=(m.getAttribute("formats")||"").split(",");for(var Q=0;Q<m.length;Q++){var Oa=(0,window.parseInt)(m[Q],10);(0,window.isNaN)(Oa)||(N=Math.max(Oa,N))}}$4(this.A,new g.vI({format:N,languageCode:l,languageName:n,name:p,kind:r,id:v,is_servable:!0,is_translateable:E,vss_id:I,is_default:z}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),p=b[e].getAttribute("lang_original"),
r=b[e].getAttribute("id"),v="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:p,id:r,is_default:v},this.F[l.languageCode]=l.languageName,this.G.push(new g.uI(l))}a()},this);
this.ce();this.B=g.OE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Ul=function(a){var b=this.D,c={v:this.C,type:"track",lang:a.A,name:a.D,kind:a.B,fmt:a.F};a.o&&(c.tlang=s4(a));return b=g.GE(b,c)};
g.h.ce=function(){c5.prototype.ce.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.ce();c5.prototype.X.call(this)};g.t(s5,g.sU);g.h=s5.prototype;g.h.X=function(){if(this.F||this.da){var a=g.jU(this.M);a&&a.zl()}else TDa(this,!1);g.sU.prototype.X.call(this)};
g.h.iC=function(){return this.ma?this.F||this.da:t5(this)?!0:PDa(this)};
g.h.load=function(a){g.sU.prototype.load.call(this);this.H=this.player.getAudioTrack();if(this.A||a)this.o&&(this.F?QDa(this,!0):a?this.zE(a,this.o):3!=this.player.Ta()&&this.A.yu(this.o,(0,g.B)(this.zE,this))),this.o&&this.o!=u5(this)?this.player.ya("captionschanged",r4(this.o)):this.player.ya("onCaptionsTrackListChanged");else{var b;this.ia?b=new h5(this.C.sa,this.player):this.C.captionTracks.length?b=new d5(this.B,this.C):b=new p5(this.C.xo,this.C.videoId,this.C.nh||this.B.nh||g.bP(this.C,"yt:cc_default_lang")||
this.B.ga,this.C.wo,this.wa,this.B);this.A=b;g.M(this,this.A);b.zu((0,g.B)(this.GV,this),!0,this.F?"vtt":void 0,this.player.getAudioTrack())}};
g.h.unload=function(){this.F&&this.o?QDa(this,!1):(this.ga&&g.Fu(this.ga),g.gU(this.player,"captions"),this.L=[],this.A&&this.A.ce(),this.J&&g.cU(this.player,this.J),this.Yw());g.sU.prototype.unload.call(this);var a=g.Y(this.player.app);a&&a.C&&g.pP(a.C.B);this.player.ya("captionschanged",{})};
g.h.GV=function(){var a;this.K||PDa(this)?a=v5(this,this.K):t5(this)&&(a=u5(this));if(this.F||this.da){for(var b=Z4(this.A.A,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.wI(e),srclang:s4(e),id:e.toString()};this.da||(f.src=this.A.Ul(e));e==a&&(f["default"]=1);c.push(g.Od("TRACK",f))}g.jU(this.M).rl(c);a=g.jU(this.M).oa();this.pa&&this.Y.R(a.textTracks,"change",this.HV)}else!this.o&&a&&x5(this,a),this.player.ya("onCaptionsTrackListChanged"),this.player.ya("onApiChange")};
g.h.HV=function(){for(var a=g.jU(this.M).oa().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=Z4(this.A.A,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&x5(this,b,!0)};
g.h.GX=function(){!this.o&&this.F||this.unload()};
g.h.zE=function(a,b,c,d){if(a){this.A.RE()&&(this.L=[],g.gU(this.M,"captions"),this.aa.Tj());var e=this.A;c=c||0;d=d||0;if(!g.w(a)){var f=new window.DataView(a);8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.oK(f,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),EDa(a)||(a=g.re(new window.Uint8Array(a))))}if(a)try{if(g.w(a)){if("WEBVTT"==a.substring(0,6)){b=a;e.o||(e.o=new a5);var k=e.o.B(b,c);.01>Math.random()&&g.tE(Error("Deprecated subtitles format in web player: WebVTT"));var l=k}else b:{k=
a;var m=g.xs(k);if(!m||!m.firstChild)throw Error("Invalid caption track data: "+k);if("timedtext"==m.firstChild.tagName){if(3==(0,window.parseInt)(m.firstChild.getAttribute("format"),10)){e.o||(e.o=new Q4(JDa(b),e.J));l=e.o.B(m,c);break b}throw Error("Unsupported subtitles format in web player: Format2");}if("transcript"==m.firstChild.tagName){e.o||(e.o=new O4(JDa(b)));var n=e.o.B(m,c);.01>Math.random()&&g.tE(Error("Deprecated subtitles format in web player: Format1"));l=n}else throw Error("Invalid caption track data: "+
k);}var p=l}else{l=a;k=d;if(!EDa(l))throw Error("Invalid binary caption track data");e.o||(e.o=new Y4(k,b));p=e.o.B(l,c)}var r=p}catch(v){g.rE(v),e.o&&e.o.dispose(),e.o=null,r=[]}else r=[];g.cU(this.player,r);if(this.K&&!this.da&&this.o!=u5(this)){!this.K||g.qN(this.B)||g.rN(this.B)||(g.Fu(this.ga),r=x4({kh:0,hg:5,fi:5,jn:2,textAlign:0,bi:0,lang:"en"}),this.V=[r],e=["Click "," for settings"],this.ka||(p=new g.YH(g.psa()),g.M(this,p),this.ka=p.element),p=r.end-r.start,(b=g.wI(this.o))&&this.V.push(new u4(r.start,
p,0,r.id,b)),this.V.push(new u4(r.start,p,0,r.id,e[0]),new u4(r.start,p,0,r.id,this.ka,!0),new u4(r.start,p,0,r.id,e[1],!0)),g.cU(this.player,this.V),g.Du(this.ga));if(this.K||g.qN(this.B))w5(this,"module-enabled",!0),this.H&&(this.H.o=this.o);(r=g.Y(this.player.app))&&r.C&&g.pP(r.C.B)}this.K=!1}};
g.h.kO=function(a){this.L.push(a);this.aa.Tj()};
g.h.lO=function(a){g.Ta(this.L,a);this.A instanceof h5&&this.A.H&&g.fU(this.player,[a]);this.aa.Tj()};
g.h.FW=function(a){if(a instanceof v4){var b=this.O[a.id];b&&b.D!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=RDa(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.MW=function(){SDa(this,this.V);this.V=null};
g.h.xG=function(){this.aa.stop();g.Zb(this.Z);this.L.sort(g.fQ);var a=this.L;if(this.J){var b=(0,g.Yd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.D)(a,this.FW,this);g.Hb(this.O,function(a,b){this.Z[b]?(a.element.parentNode||g.iU(this.player,a.element,4),a.mj(this.Z[b])):(a.dispose(),delete this.O[b])},this)};
g.h.jF=function(){q5(this,{},!0)};
g.h.lt=function(){var a=y5.Lb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Bf?3:a.bold?1:a.Bf?2:0,textOpacity:a.textOpacity,windowColor:y5.windowColor,windowOpacity:y5.windowOpacity};var b=r5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.bx=function(a,b){var c={};g.Da(c,r5(this,"display-settings"));g.Da(c,a);q5(this,c,b);this.player.U("captionssettingschanged")};
g.h.Yw=function(){!this.F&&this.loaded&&(g.Hb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.xG())};
g.h.Mu=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.md(b,-2,4);this.bx({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&x5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.B.Mb&&w5(this,"module-enabled",!!b);break;case "track":if(!this.A)return{};if(b){if(this.F)break;if(!g.za(b))break;if(g.Yb(b)){x5(this,null,!0);break}var d;c=Z4(this.A.A,!0);for(var e=0;e<c.length;e++){var f=c[e];f.A!=b.languageCode||d&&f.C!=b.languageName||(d=b.translationLanguage?
gDa(f,b.translationLanguage,this.wa):f)}!d||d==this.o&&this.loaded||x5(this,d,!0)}else return this.loaded&&this.o&&this.o!=u5(this)?r4(this.o):{};return"";case "tracklist":return this.A?(0,g.J)(Z4(this.A.A,!(!b||!b.includeAsr)),function(a){return r4(a)}):[];
case "translationLanguages":return this.A?this.A.G:[];case "displaySettings":d=this.lt();if(g.qN(this.B)&&b&&g.za(b))if(b.reset)this.jF();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=UDa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=VDa(b[c],d[c]);break;case "charEdgeStyle":var k=g.m1[b[c]];f[c]=g.sa(k)?k:d[c];break;case "fontSizeIncrement":f[c]=WDa(b[c],d[c]);break;case "fontFamilyOption":k=g.l1[b[c]];f.fontFamily=
g.sa(k)?k:d[c];break;case "fontStyle":k=g.n1[b[c]],f[c]=g.sa(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.bx(f,!0);d=this.lt()}d.fontFamilyOption=g.Sya[d.fontFamily];d.charEdgeStyle=g.Tya[d.charEdgeStyle];d.fontStyle=g.Uya[d.fontStyle];return d;case "sampleSubtitles":this.F||void 0==b||TDa(this,!!b);break;case "xmlTrack":b&&this.B.Mb&&(this.F||x5(this,new g.vI({languageName:b.name}),!1,b.xml))}};
g.h.iO=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.B.Mb&&a.push("stickyLoading","xmlTrack");return a};
g.h.jO=function(){var a=this.o;return a?{cc:a.G}:{}};
g.h.mG=function(){this.loaded&&this.o&&this.o!=u5(this)?(w5(this,"module-enabled",!1),this.unload(),t5(this,!0)&&x5(this,u5(this),!1)):x5(this,this.o==u5(this)?v5(this,!0):this.o,!0)};
g.h.UR=function(){var a=this.o==u5(this);t5(this,a)?x5(this,this.player.getAudioTrack().Xo,!1):this.C.captionTracks.length&&(this.loaded&&this.unload(),this.iC()&&(a?x5(this,v5(this),!1):this.load()))};g.rX.captions=s5;})(_yt_player);
