(function(g){var window=this;var A5=function(a,b,c){var d=b.Qa();g.U(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.ld(c?c:"mqdefault.jpg");var f=b instanceof g.QO&&b.lengthSeconds?g.TU(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.hQ(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.QO?b.Ja:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.sl||g.JU("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Wl(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.jQ&&(d.playlist_length=b.getLength());a.update(d)},B5=function(a,b){g.dI.call(this,{I:"div",
ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},C5=function(a){g.V.call(this,{I:"div",
N:"ytp-upnext",T:{"aria-label":"{{aria_label}}"},P:[{I:"div",N:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-upnext-top",P:[{I:"span",N:"ytp-upnext-header",ca:"Up Next"},{I:"span",N:"ytp-upnext-title",ca:"{{title}}"},{I:"span",N:"ytp-upnext-author",ca:"{{author}}"}]},{I:"a",N:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Play next video"},P:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",N:"ytp-svg-autoplay-circle",
T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",N:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",N:"ytp-upnext-bottom",P:[{I:"span",N:"ytp-upnext-cancel"},{I:"span",N:"ytp-upnext-paused",ca:"Autoplay is paused"}]}]});this.F=null;
var b=this.o["ytp-upnext-cancel"];this.F=new g.V({I:"button",ea:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancel autoplay"},ca:"Cancel"});g.M(this,this.F);this.F.W("click",this.cS,this);this.F.xa(b);this.B=a;this.L=this.o["ytp-svg-autoplay-ring"];this.H=this.G=this.C=this.D=null;this.J=new g.Cu(this.Bo,5E3,this);g.M(this,this.J);this.K=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.oU);this.ND();this.R(a,"autonavvisibility",this.ND);this.R(a,"mdxnowautoplaying",
this.BT);this.R(a,"mdxautoplaycanceled",this.CT);this.R(a,"mdxautoplayupnext",this.AG);3==this.B.Ta()&&(a=(a=g.RT(g.LT(this.B)))?a.aL():null)&&this.AG(a)},D5=function(a,b){if(!a.C){g.uG("a11y-announce","Up Next "+a.D.title);
a.K=g.EG();a.C=new g.Cu((0,g.B)(a.Xr,a,b),25);a.Xr(b);var c=b||g.X(a.B).experiments.A("autoplay_time")||1E4;a.B.ya("onAutonavCoundownStarted",c)}g.Nq(a.element,"ytp-upnext-autoplay-paused")},F5=function(a){E5(a);
a.K=g.EG();a.Xr();g.T(a.element,"ytp-upnext-autoplay-paused")},E5=function(a){a.C&&(a.C.dispose(),a.C=null)},G5=function(a,b){b=void 0===b?!1:b;
if(g.X(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=a.D.Qa(),a.Bo(),a.G=new window.Notification("Up Next",{body:c.title,icon:c.ld()}),a.H=a.R(a.G,"click",a.eU),a.J.start())}E5(a);a.B.yk(!1,b)},aEa=function(a){B5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.V({I:"div",N:"ytp-subscribe-card",P:[{I:"img",N:"ytp-author-image",T:{src:b.profilePicture}},{I:"div",N:"ytp-subscribe-card-right",P:[{I:"div",N:"ytp-author-name",ca:b.author},{I:"div",N:"html5-subscribe-button-container"}]}]});g.M(this,this.B);this.B.xa(this.element);this.C=new g.CZ("Subscribe",null,"Unsubscribe",null,!0,!1,b.fl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.C);this.C.xa(this.B.o["html5-subscribe-button-container"]);this.hide()},H5=
function(a){var b=g.X(a),c=g.RI||g.qf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.V.call(this,{I:"a",ea:e,T:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-videowall-still-info",P:[{I:"span",N:"ytp-videowall-still-info-bg",P:[{I:"span",N:"ytp-videowall-still-info-content",T:c,P:[{I:"span",N:"ytp-videowall-still-info-title",ca:"{{title}}"},{I:"span",
N:"ytp-videowall-still-info-author",ca:"{{author_and_views}}"},{I:"span",N:"ytp-videowall-still-info-live",ca:"Live"},{I:"span",N:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{I:"span",ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",N:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",ca:"{{playlist_length}}"},")"]}]},{I:"span",ea:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
P:[{I:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",N:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.F=d;this.B=a;this.C=null;this.D=new g.bG(this);g.M(this,this.D);this.W("click",this.H);this.W("keypress",this.J);this.D.R(a,"videodatachange",this.G);g.X(a).V&&(a=a.app.ia,b=this.element,g.Na(a.o,b),g.Ra(a.o,b),c=String(a.K++),b.setAttribute("data-visual-id",c),g.lf(this,(0,g.B)(a.J,a,b)));this.G()},I5=function(a){B5.call(this,a,"videowall-endscreen");
this.K=a;this.G=0;this.C=[];this.H=this.F=this.D=null;this.J=this.O=!1;this.Y=new g.bG(this);g.M(this,this.Y);this.L=new g.Cu(g.Ca(g.T,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.V({I:"button",ea:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Previous"},P:[g.MU()]});g.M(this,b);b.xa(this.element);b.W("click",this.aQ,this);this.M=new g.YH({I:"div",N:"ytp-endscreen-content"});g.M(this,this.M);this.M.xa(this.element);b=new g.V({I:"button",ea:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":"Next"},P:[g.NU()]});g.M(this,b);b.xa(this.element);b.W("click",this.ZP,this);this.B=new C5(a);g.M(this,this.B);g.iU(this.player,this.B.element,4);this.hide()},J5=function(a){return g.kU(a.player)&&a.Zy()&&!a.H},bEa=function(a,b){return(0,g.J)(b.suggestions,function(b){b=g.wX(g.X(a.K),b);
g.M(a,b);return b})},K5=function(a){var b=a.gv();
b!=a.O&&(a.O=b,a.player.U("autonavvisibility"))},L5=function(a){g.sU.call(this,a);
this.o=null;this.A=new g.bG(this);g.M(this,this.A);this.B=g.X(a);cEa(a)?this.o=new I5(this.player):this.B.Ma?this.o=new aEa(this.player):this.o=new B5(this.player);g.M(this,this.o);g.iU(this.player,this.o.element,4);this.iF();this.A.R(a,"videodatachange",this.iF,this);this.A.R(a,g.gQ("endscreen"),this.aO,this);this.A.R(a,"crx_endscreen",this.bO,this)},cEa=function(a){a=g.X(a);
return a.Ha&&!a.Ma};
g.t(B5,g.dI);B5.prototype.create=function(){this.created=!0};
B5.prototype.destroy=function(){this.created=!1};
B5.prototype.Zy=function(){return!1};
B5.prototype.gv=function(){return!1};g.t(C5,g.V);g.h=C5.prototype;g.h.Bo=function(){this.G&&(this.J.stop(),this.Ka(this.H),this.H=null,this.G.close(),this.G=null)};
g.h.ND=function(){g.cI(this,g.MT(this.B))};
g.h.eU=function(){window.focus();this.Bo()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Xr=function(a){a=a||g.X(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.EG()-this.K,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.Ta()?G5(this,!0):this.C&&this.C.start()};
g.h.oU=function(a){!g.ce(this.F.element,g.QF(a))&&g.wW(a,this.B)&&G5(this)};
g.h.cS=function(){g.OT(this.B,!0)};
g.h.BT=function(a){this.B.Ta();this.show();D5(this,a)};
g.h.AG=function(a){this.B.Ta();this.D&&this.D.Qa().videoId==a.Qa().videoId||(this.D=a,A5(this,a,"hqdefault.jpg"))};
g.h.CT=function(){this.B.Ta();E5(this);this.hide()};
g.h.X=function(){E5(this);this.Bo();g.V.prototype.X.call(this)};g.t(aEa,B5);g.t(H5,g.V);H5.prototype.Tk=function(){g.nU(this.B,this.element);var a=this.C.Qa().videoId,b=this.C.getPlaylistId();g.$_(this.B.app,a,this.C.Kd,b,void 0,void 0,void 0)};
H5.prototype.H=function(a){g.wW(a,this.B,this.F,this.C.Kd||void 0)&&this.Tk()};
H5.prototype.J=function(a){switch(a.keyCode){case 13:case 32:g.VF(a)||(this.Tk(),g.UF(a))}};
H5.prototype.G=function(){var a=this.B.getVideoData(),b=g.X(this.B);this.F=a.isDni?!1:b.o};g.t(I5,B5);g.h=I5.prototype;g.h.create=function(){B5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.D=bEa(this,a),this.F=a);this.Ug();this.Y.R(this.player,"appresize",this.Ug);this.Y.R(this.player,"onVideoAreaChange",this.Ug);this.Y.R(this.player,"videodatachange",this.bQ);this.Y.R(this.player,"autonavchange",this.HC);this.Y.R(this.player,"autonavcancel",this.YP);this.Y.R(this.element,"transitionend",this.IV)};
g.h.destroy=function(){g.dG(this.Y);g.nf(this.C);this.C=[];this.D=null;B5.prototype.destroy.call(this);g.Nq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Zy=function(){return 1!=this.F.autonavState};
g.h.show=function(){B5.prototype.show.call(this);g.Nq(this.element,"ytp-show-tiles");g.X(this.player).B?g.Eu(this.L):this.L.start();(this.J||this.H&&this.H!=this.F.clientPlaybackNonce)&&g.OT(this.player,!1);J5(this)?(K5(this),2==this.F.autonavState?g.X(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.Zi()?G5(this.B,!0):D5(this.B):3==this.F.autonavState&&F5(this.B)):(g.OT(this.player,!0),K5(this))};
g.h.hide=function(){B5.prototype.hide.call(this);F5(this.B);K5(this)};
g.h.IV=function(a){g.QF(a)==this.element&&this.Ug()};
g.h.Ug=function(){if(this.D&&this.D.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.$T(this.K,!0),b=g.sI(this.K);b&&(b=b.od()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.D.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,v=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(v)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.md(a.width/m||1,1,1.21);n*=g.md(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Ph(a,m,n);g.xh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.D[0];c.D=f;A5(c,f,"hqdefault.jpg");g.U(this.element,"ytp-endscreen-takeover",J5(this));K5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.nd(p+this.G,l),0!=r){v=this.C[c];v||(v=new H5(this.player),this.C[c]=v,a.appendChild(v.element));z=Math.floor(n*k/e);var E=Math.floor(m*f/b),I=Math.floor(n*(k+r)/e)-z-4,N=Math.floor(m*(f+r)/b)-E-4;g.Eh(v.element,E,z);g.Ph(v.element,N,I);g.xh(v.element,"transitionDelay",(k+f)/20+"s");g.U(v.element,"ytp-videowall-still-mini",1==r);g.U(v.element,"ytp-videowall-still-large",2<r);r=v;p=this.D[p];r.C!=p&&(r.C=p,A5(r,p,g.Lq(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),v=(p=p.Kd)&&p.itct)&&(p=r.B,g.X(p).V&&(p=p.app.ia,r=r.element,z=r.getAttribute("data-visual-id"),g.Na(p.o,r),p.A?v&&(r.visualElement=g.cH(v)):g.lU(p,"onLogServerVeCreated",{id:z,tracking_params:v})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.C.length-1;b>=c;b--)e=this.C[b],g.Xd(e.element),g.mf(e);this.C.length=c}};
g.h.bQ=function(){var a=this.player.getVideoData();this.F!=a&&(this.G=0,this.D=bEa(this,a),this.F=a,this.Ug())};
g.h.ZP=function(){this.G+=this.C.length;this.Ug()};
g.h.aQ=function(){this.G-=this.C.length;this.Ug()};
g.h.cN=function(){return!!this.B.C};
g.h.HC=function(a){1==a?(this.J=!1,this.H=this.F.clientPlaybackNonce,E5(this.B),this.A&&this.Ug()):(this.J=!0,this.A&&J5(this)&&(2==a?D5(this.B):3==a&&F5(this.B)))};
g.h.YP=function(a){if(a){for(a=0;a<this.C.length;a++)g.oU(this.K,this.C[a].element,!0);this.HC(1)}else this.H=null,this.J=!1;this.Ug()};
g.h.gv=function(){return this.A&&J5(this)};g.t(L5,g.sU);g.h=L5.prototype;g.h.hC=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!cEa(this.player)||b;a=g.fP(a,"ypc_module");var c=g.D_(this.player.app);return b&&!a&&!c};
g.h.gC=function(){return this.o.gv()};
g.h.YM=function(){return this.gC()?this.o.cN():!1};
g.h.X=function(){g.gU(this.player,"endscreen");g.sU.prototype.X.call(this)};
g.h.load=function(){g.sU.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.sU.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.aO=function(a){this.hC()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.bO=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.iF=function(){g.gU(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.eQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.M(this,a);var b=new g.eQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.M(this,b);g.cU(this.player,[a,b])};g.rX.endscreen=L5;})(_yt_player);
